### PR TITLE
fix: support current librouteros login_method API

### PR DESCRIPTION
**Pull request by Komzpa**
## Summary
Fix MikroTik login for current `librouteros` versions by:
- using the correct `login_method` keyword instead of `login_methods`
- resolving legacy string config values like `plain` to the callable expected by `librouteros.connect`

## Problem
With current Home Assistant / Python / `librouteros`, the integration's login path is broken:

1. `librouteros.connect` expects `login_method=...`, not `login_methods=...`
2. the value must be a callable such as `librouteros.login.plain`, not the string `'plain'`

`master` currently still does:
```python
kwargs = {
    "encoding": self._encoding,
    "login_methods": self._login_method,
    "port": self._port,
}
```

That causes failures like:
- `connect() got an unexpected keyword argument 'login_methods'`
- `'str' object is not callable`

## Reproduction
Observed on a live Home Assistant 2026.4.3 installation with `mikrotik_router` v2.2-style code and current `librouteros` behavior.

The issue matches the family of breakages reported after HA 2026.4 updates, for example #477.

## Fix
Keep backward compatibility with existing config values:
- if `self._login_method` is already callable, pass it through
- if it is a string such as `plain`, resolve it via `librouteros.login`

## Verification
- `python3 -m compileall custom_components/mikrotik_router/mikrotikapi.py`
- verified the equivalent patch live in Home Assistant: the integration recovered from setup failures and resumed reporting entities

## Reference
`librouteros` documents `login_method` as a callable and shows `from librouteros.login import plain, token`:
https://librouteros.readthedocs.io/en/latest/connect.html

## Summary by Sourcery

Bug Fixes:
- Update connection parameters to use the correct librouteros login_method keyword and resolve string-based login method configuration to the expected callable.

### CODE REVIEW

**Comment by caseynisu** [comment]
# Bug Fix: "unexpected keyword 'login_methods'" Connection Error

### Issue Description
When attempting to connect to a MikroTik router, the integration fails with the following error:
`Cannot connect to Mikrotik API: unexpected keyword 'login_methods'`

### Root Cause
The error is caused by a mismatch between this custom component and the underlying `librouteros` library:
1. **Keyword Mismatch:** This component passes `login_methods` (plural), while `librouteros` [at line 75](https://github.com/luqasz/librouteros/blob/main/src/librouteros/__init__.py) expects `login_method` (singular).
2. **Type Mismatch:** `librouteros` expects a **callable** (e.g., the `plain` or `token` function from its [login.py](https://github.com/luqasz/librouteros/blob/main/src/librouteros/login.py)), but a **string** is currently being passed by this component.

### Proposed Solution
Since `librouteros` defaults to the `plain` login method automatically and this component currently only supports plain authentication, there is no need to explicitly define it. Removing the param allows the library to use its stable default.

### Changes Required
In `custom_components/mikrotik_router/mikrotikapi.py`, comment/remove the `login_methods` entry from the `kwargs` dictionary at line 120.

**Fix:**
```python
        kwargs = {
            "encoding": self._encoding,
          #  "login_methods": self._login_method,  --> Comment this at line no 120
            "port": self._port,
        }

**Comment by Komzpa** [comment]
@tomaae ping, the bot marks this stale but it's all still an issue, can you have a look please?

**Comment by Komzpa** [comment]
@tomaae hello. is there anyone else who can merge this while you're not available?

**Comment by codedumper1** [comment]
Is this project officially abandoned? Releasing a version with a broken connection mechanism that completely bricked the tool, and then ignoring community PRs that fix it, is unacceptable. This is impacting everyone relying on this repository. Can someone with merge rights please step in and approve the pending fix?

**Comment by Komzpa** [comment]
@tomaae if you have 5 minutes to push merge here the users will be able to at keep using it as is

**Comment by tomaae** [comment]
why are you trying to downgrade connection library tho? I know old one had some issues, cant remember now since it was long time ago.

**Comment by ChristopherJohnKelly** [comment]
@tomaae 

This isn't a downgrade.

1. **The login is broken on librouteros ≥ 4.1**. The component calls `librouteros.connect(..., login_methods=...)`, but `connect()` no longer accepts that argument as of 4.1, so login fails with `TypeError: unexpected keyword argument 'login_methods'` and the integration can't connect. `librouteros` is at 4.1.1 today, so a clean install that resolves `librouteros>=3.4.1` pulls 4.1.1 and is broken out of the box.

2. **It usually keeps working only because of the core Mikrotik integration**. Many of us run this alongside HA's built-in mikrotik integration, which pins `librouteros==3.2.1`. HA has a single shared Python environment, so on load that pin often wins resolution and librouteros lands on 3.2.1 — where this component still works, despite this repo requesting >=3.4.1. It's incidental, and it flaps: when resolution instead lands on 4.1.x, connections break (which matches the recent wave of reports).

3. What this PR implements:
- Fixes the login to use librouteros' current login_method API, with a runtime check so it works on both older and 4.1+ builds.
- Lowers the requirement to librouteros>=3.2.0. >= still allows the newest library, so nobody is forced onto an older version; it just makes the floor consistent with the 3.2.1 that's already commonly installed via core, so the two integrations stop fighting over the version.

Net effect: the component connects whether librouteros resolves to 3.2.1 or 4.1.1, instead of only working when core happens to hold it back.

**Comment by bygadd** [comment]
Confirmed on HA Core 2026.7.0 / Python 3.14 — this fixes the `connect() got an unexpected keyword argument 'login_methods'` crash.

Worth flagging for others hitting this: it also takes down HA's **built-in `mikrotik`** integration at the same time, because both share the venv's `librouteros`. The trigger is that `manifest.json` requires `librouteros>=3.4.1` with no upper bound, so pip pulls 4.x (which dropped the old `**kwargs` `connect()` signature that the code relies on). As a quick workaround until this lands, pinning `librouteros==3.2.1` (or `>=3.4.1,<4`) in the manifest restores both integrations.

Thanks for the fix — hoping it gets merged. — Diagnosed with AI assistance.

**Comment by Nikolay-Ch** [comment]
@tomaae
Could you please let me know when this PR might be merged? Quite a few of us are unable to use the extension because it crashes on HA startup. It seems like the only option left is to uninstall it since it's currently not working.

**Comment by keithstrachan** [comment]
not stale, still an issue, needs to be addressed.
disappointed as i was looking forward to managing my devices with this addon.

@tomaae please find time and remediate this asap. right now, your tool does not work. 
if you don't have time, add people to your project so that they can merge.
