### PR TITLE
Fix librouteros 4.x login, OptionsFlow, and RouterOS version parsing

### LINKED ISSUE #418: [Warning] Sets option flow config_entry explicitly, which is deprecated
From HA logs:

Detected that custom integration 'mikrotik_router' sets option flow config_entry explicitly, which is deprecated at custom_components/mikrotik_router/config_flow.py, line 178: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/tomaae/homeassistant-mikrotik_router/issues

### LINKED ISSUE #488: [Bug] Cannot connect to Mikrotik API: unexpected keyword 'login_methods'
## Describe the issue
When trying to configure or connect to a Mikrotik router, the integration fails to authenticate. The issue stems from recent changes in the underlying librouteros library, which introduced two breaking changes in how the login method is passed during the connect() call:

The parameter 'login_methods' was renamed to 'login_method'.

It no longer accepts a string ("plain" or "token") and now requires the actual callable function.

`ERROR (MainThread) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.x.x error while connecting: connect() got an unexpected keyword argument 'login_methods'. Did you mean 'login_method'?
`
## How to reproduce the issue
Go to Settings -> Devices & Services in Home Assistant.

Attempt to add or configure the Mikrotik Router integration.

Enter valid IP, username, password, and port.

Click Submit.

See the connection failure in the UI and the fatal errors in the Home Assistant logs.

## Software versions
-  Home Assistant version: 2026.4.4
- Mikrotik Router version: 2.2
- Router OS version: 7.22
- Mikrotik hAP AX^3 

## Traceback/Error logs
First error (due to parameter name change):
ERROR (MainThread) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.x.x error while connecting: connect() got an unexpected keyword argument 'login_methods'. Did you mean 'login_method'?

Second error (if parameter is renamed manually, due to string vs callable change):
ERROR (MainThread) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.x.x error while connecting: 'str' object is not callable

## Additional context
I have successfully patched this locally by doing the following in custom_components/mikrotik_router/mikrotikapi.py:

Importing the functions at the top:
from librouteros.login import plain, token

Updating the kwargs dictionary inside the connect() method from this:
"login_methods": self._login_method,

To this:
"login_method": plain if self._login_method == "plain" else token,

### LINKED ISSUE #492: Version format '7.23 (stable)' not recognized – regex requires 3 version components
## Describe the issue

Since RouterOS 7.23, MikroTik devices report their firmware version as `7.23 (stable)` — a two-component version string. The integration's version parser in `coordinator.py` uses a regex that requires exactly three components (`major.minor.patch`), so it fails to parse the version and logs an error every polling cycle for all affected devices.

```
Mikrotik 192.168.100.248 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.254 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.247 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.249 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
```

After the error the function returns early, so `major_fw_version` / `minor_fw_version` are never set for any of the affected devices.

## How to reproduce the issue

1. Update any MikroTik device to RouterOS 7.23 (stable).
2. Reload the Mikrotik Router integration.
3. Observe the error in the Home Assistant log.

## Expected behavior

The integration parses `7.23 (stable)` correctly and sets `major_fw_version = 7`, `minor_fw_version = 23`.

## Screenshots

N/A

## Software versions

- Home Assistant version: 2026.5.4
- Mikrotik Router integration version: 0.0.99-dev
- Mikrotik Hardware: RB3011UiAS, RB2011UiAS-2HnD, RB750Gr3, RB750GL
- RouterOS version: 7.23 (stable)

## Diagnostics data

N/A

## Traceback/Error logs

```
Logger: custom_components.mikrotik_router.coordinator
Source: custom_components/mikrotik_router/coordinator.py:1586

Mikrotik 192.168.100.248 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.254 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.247 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
Mikrotik 192.168.100.249 unable to determine major/minor FW version ('7.23 (stable)'): Version format is not recognized.
```

## Additional context

The failing line in `coordinator.py:1580`:

```python
version_match = re.match(r"^(\d+)\.(\d+)\.(\d+)", full_version)
```

Since only `major` (group 1) and `minor` (group 2) are ever used, the patch component in the regex is unnecessary. The fix is to make it optional or drop it entirely:

```python
version_match = re.match(r"^(\d+)\.(\d+)", full_version)
```

### LINKED ISSUE #498: Fix compatibility with librouteros 4.x and recent Home Assistant versions
## Problem
After a fresh HACS install on a recent Home Assistant version, the integration fails to connect with three separate bugs.

**Environment:**
- Home Assistant 2026.6
- librouteros 4.0.1
- Python 3.14

---

## Bug 1: `login_methods` → `login_method` (mikrotikapi.py)

librouteros 4.x renamed the parameter from `login_methods` to `login_method`.

**Fix in `mikrotikapi.py` (~line 120):**
Change:
"login_methods": self._login_method,
To:
"login_method": self._login_method,

---

## Bug 2: `DEFAULT_LOGIN_METHOD` is a string, not callable (mikrotikapi.py)

librouteros 4.x expects `login_method` to be a callable function, not a string like `"plain"`.

**Fix in `mikrotikapi.py` (top of file):**
Remove the import of `DEFAULT_LOGIN_METHOD` from `const.py` and replace with:
from librouteros.login import plain as DEFAULT_LOGIN_METHOD

---

## Bug 3: `config_entry` setter error in Options Flow (config_flow.py)

Recent Home Assistant versions set `config_entry` automatically in OptionsFlow. 
Manually assigning it in `__init__` causes a 500 error when opening integration options.

**Fix in `config_flow.py` in `MikrotikControllerOptionsFlowHandler.__init__`:**
Remove:
self.config_entry = config_entry

The line `self.options = dict(config_entry.options)` can stay as-is.

---

All three fixes were tested and confirmed working. Happy to provide more details if needed.

### PR DESCRIPTION
**Pull request by zlatko-lakisic**
## Proposed change
Fixes several compatibility breakages with current Home Assistant and `librouteros` 4.x / RouterOS 7:

1. **Login API** — resolve `login_method` as a callable (`plain`/`token`) and keep a 3.x ↔ 4.x fallback when the installed library still expects `login_methods`.
2. **Options flow** — stop assigning `OptionsFlow.config_entry` in `__init__` (HA sets it automatically; assigning it fails on recent releases).
3. **Firmware version parsing** — accept RouterOS strings like `7.23 (stable)` in the coordinator and update changelog path.

Related / closes overlapping reports: fixes #488, fixes #492, fixes #418, fixes #498.

There is already an open login-focused PR (#486). This change covers that login breakage and the OptionsFlow + version-parser issues as well.

## Type of change
- [x] Bugfix
- [ ] New feature
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Additional information
Tested against current Home Assistant with `librouteros` 4.x and RouterOS 7 devices reporting channel suffixes in the firmware version string.

Fork used for validation: https://github.com/zlatko-lakisic/hacs-mikrotik_router

## Checklist
- [x] The code change is tested and works locally.
- [ ] The code has been formatted using Black.
- [ ] Tests have been added to verify that the new code works.
- [ ] Documentation added/updated if required.

Made with [Cursor](https://cursor.com)

## Summary by Sourcery

Restore compatibility of the Mikrotik Router integration with newer Home Assistant, librouteros 4.x, and RouterOS 7 version formats.

Bug Fixes:
- Make librouteros connection handling compatible with both 3.x and 4.x login APIs, including fallback between login_method and login_methods and clearer error reporting for API mismatches.
- Adjust the options flow to rely on Home Assistant's injected config_entry and avoid assigning it in the initializer to prevent failures on recent HA versions.
- Update firmware version parsing to correctly extract major and minor RouterOS versions from strings that include channel suffixes such as "7.23 (stable)", and improve error logging when parsing fails.
- Normalize RouterOS version strings with channel suffixes before generating changelog version ranges so that version comparisons work correctly.

Enhancements:
- Refactor login handling helpers and version normalization utilities to centralize compatibility logic and reduce duplication.

### CODE REVIEW

**Comment by zlatko-lakisic** [comment]
Addressed the Sourcery feedback in the latest commit:

- Removed \`OptionsFlow.__init__\` entirely; options are initialized in \`async_step_init\`
- Narrowed the \`TypeError\` retry path in \`connect()\` to login_method/login_methods mismatches
- Centralized RouterOS version normalization/parsing in \`helper.py\` for coordinator + update changelog generation

**Comment by zlatko-lakisic** [comment]
@tomaae please review!

**Comment by tomaae** [comment]
This looks really good. I dont have time to test it personally at the moment tho.
