### PR TITLE
Fix for ros 7.13 wireless

### PR DESCRIPTION
**Pull request by slackr31337**
## Proposed change
Update to coordinator for RouterOS > 7.12 with new wifi packages

## Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Checklist

- [x] The code change is tested and works locally.
- [x] The code has been formatted using Black.
- [x] Tests have been added to verify that the new code works.
- [x] Documentation added/updated if required.

### CODE REVIEW

File: custom_components/mikrotik_router/coordinator.py [hunk 1]
```diff
@@ -284,13 +284,16 @@ def __init__(self, hass: HomeAssistant, config_entry: ConfigEntry):
         self.host_tracking_initialized = False
 
         self.support_capsman = False
+        self.support_wifi = False
         self.support_wireless = False
         self.support_wifiwave2 = False
         self.support_ppp = False
         self.support_ups = False
         self.support_gps = False
+        self._wifimodule = None
```
Comment (tomaae) [inline custom_components/mikrotik_router/coordinator.py:293]: this would break all current installations. default path needs to be wireless
`self._wifimodule = "wireless"`

File: custom_components/mikrotik_router/coordinator.py [hunk 2]
```diff
@@ -517,10 +520,37 @@ def get_capabilities(self):
             self.support_wireless = True
             if "wifiwave2" in packages and packages["wifiwave2"]["enabled"]:
                 self.support_wifiwave2 = True
+                self.support_wifi = False
                 self.support_capsman = False
+                self._wifimodule = "wifiwave2"
+                
+            elif "wifi" in packages and packages["wifi"]["enabled"]:
+                self.support_wifiwave2 = False
```
Comment (tomaae) [inline custom_components/mikrotik_router/coordinator.py:528]: with this change, self.support_wifiwave2 and self.support_wifi are most likely unused variables.

File: custom_components/mikrotik_router/coordinator.py [hunk 3]
```diff
@@ -1553,14 +1583,23 @@ def get_firmware_update(self) -> None:
 
         if self.ds["fw-update"]["installed-version"] != "unknown":
             try:
-                self.major_fw_version = int(
```
Comment (tomaae) [inline custom_components/mikrotik_router/coordinator.py:1556]: this block change is most likely not necessery, as it is used to control only capsman selection, which is erroneous.

File: custom_components/mikrotik_router/coordinator.py (hunk 1 above)
Comment (slackr31337) [reply custom_components/mikrotik_router/coordinator.py:293]: Fixing

File: custom_components/mikrotik_router/coordinator.py [hunk 4]
```diff
@@ -1952,9 +1991,18 @@ def get_dhcp_network(self) -> None:
...
+            self._wifimodule = "wifi"
+            
+        else:
+            registration_path= "/caps-man/registration-table"
+            self._wifimodule = "wireless"
+            
         self.ds["capsman_hosts"] = parse_api(
             data={},
-            source=self.api.query("/caps-man/registration-table"),
+            source=self.api.query(registration_path),
```
[the remark this answers is not in the document]
Comment (slackr31337) [reply custom_components/mikrotik_router/coordinator.py:2005]: The caps-man path changed in 7.13 and the code fails with an exception if not changed.

File: custom_components/mikrotik_router/coordinator.py (hunk 2 above)
Comment (slackr31337) [reply custom_components/mikrotik_router/coordinator.py:528]: Okay, removing self.support_wifiwave2 and self.support_wifi

File: custom_components/mikrotik_router/coordinator.py (hunk 3 above)
Comment (slackr31337) [reply custom_components/mikrotik_router/coordinator.py:1556]: I changed this to add self.minor_fw_version so that get_capsman_hosts can check the minor version > 12. In verison 7.13 the capsman path is no longer /caps-man... and the registration table in under /interface/wifi/registration-table.

**Comment by tomaae** [comment]
Did you test this with wifi/wifi-qcom/wifi-qcom-ac modules disabled or not installed?
Not sure how it works in 7.13, but integration may crash in that case.

**Comment by SkeLLLa** [comment]
@tomaae 
I just have such device, where neither wifi, nor old wireless package installed. So in the package list there are no packages except routeros. 

On routeros >=7.13, if you have no extra wifi packages, the route `interface/wifi/registration-table` is available, so this fix should work fine. I can doublecheck it on real device through hacs after merging to master or releasing some beta version.

**Comment by L2jLiga** [comment]
Checked on my CCR1008-8G-1S-1S+

ROS 7.13.0
no wireless package

image

File: custom_components/mikrotik_router/coordinator.py [hunk 5]
```diff
@@ -516,11 +517,28 @@ def get_capabilities(self):
             self.support_ppp = True
             self.support_wireless = True
```
Comment (L2jLiga) [inline custom_components/mikrotik_router/coordinator.py:518]: problem comes from here, 

I guess the solution could be to remove assigning True from here and add it in every branch as is, except the last one, in last one we have to check whether we on 7.13 and newer or not:

```python
        elif 0 < self.major_fw_version >= 7:
            self.support_ppp = True
            if "wifiwave2" in packages and packages["wifiwave2"]["enabled"]:
                self.support_capsman = False
                self.support_wireless = True
                self._wifimodule = "wifiwave2"

            elif "wifi" in packages and packages["wifi"]["enabled"]:
                self.support_capsman = False
                self.support_wireless = True
                self._wifimodule = "wifi"

            elif "wifi-qcom" in packages and packages["wifi-qcom"]["enabled"]:
                self.support_capsman = False
                self.support_wireless = True
                self._wifimodule = "wifi"

            elif "wifi-qcom-ac" in packages and packages["wifi-qcom-ac"]["enabled"]:
                self.support_capsman = False
                self.support_wireless = True
                self._wifimodule = "wifi"

            else:
                self.support_capsman = True
                self.support_wireless = self.major_fw_version >= 7 and self.minor_fw_version < 13
```

Comment (L2jLiga) [reply custom_components/mikrotik_router/coordinator.py:518]: At least this solution works fine for my setup

Comment (slackr31337) [reply custom_components/mikrotik_router/coordinator.py:518]: Hello, I've updated the PR to include this. I have also tested this code on a CSR309-1G-8S+ on 7.13, hAP ac3 on 7.13 and CRS328-24P-4S+ on 7.13. I didn't test on < 7.13

**Comment by slackr31337** [comment]
> Did you test this with wifi/wifi-qcom/wifi-qcom-ac modules disabled or not installed? Not sure how it works in 7.13, but integration may crash in that case.

Yes, I have tested this on a CRS309-1G-8S+ with only the routeros package installed.

**Comment by Yamaha0014** [comment]
Hi is it possible upload corrected  file coordinator.py ? On pastebin or another service?

**Comment by slackr31337** [comment]
> Hi is it possible upload corrected file coordinator.py ? On pastebin or another service?



> Hi is it possible upload corrected file coordinator.py ? On pastebin or another service?

https://raw.githubusercontent.com/slackr31337/homeassistant-mikrotik_router/ros-7.13/custom_components/mikrotik_router/coordinator.py

**Comment by ilwalti** [comment]
Nope...

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 13:57:29 (1 occurrences)
Last logged: 13:57:29

Setup failed for custom integration 'mikrotik_router': Unable to import component: cannot import name 'CONF_SENSOR_NETWATCH_TRACKER' from 'custom_components.mikrotik_router.const' (/config/custom_components/mikrotik_router/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mikrotik_router/__init__.py", line 16, in <module>
    from .coordinator import MikrotikData, MikrotikCoordinator, MikrotikTrackerCoordinator
  File "/config/custom_components/mikrotik_router/coordinator.py", line 33, in <module>
    from .const import (
ImportError: cannot import name 'CONF_SENSOR_NETWATCH_TRACKER' from 'custom_components.mikrotik_router.const' (/config/custom_components/mikrotik_router/const.py)

**Comment by erkedocara** [comment]
this custom repo didn't worked for me 
image
image

**Comment by VolodymyrLykhachov** [comment]
It works for me after adding: 
CONF_SENSOR_NETWATCH_TRACKER = "sensor_netwatch"
DEFAULT_SENSOR_NETWATCH_TRACKER = False
after line 60
to /config/custom_components/mikrotik_router/const.py

**Comment by sermayoral** [comment]
You can also change the mikrotik custom component to master branch in HACS, after that update de coordinator.py of this branch and restart HA

**Comment by im-kulikov** [comment]
it works without any changes for me 👍

**Comment by jajera** [comment]
it worked for me with on hap ax2 after changing to this.

```bash
CONF_SENSOR_NETWATCH_TRACKER = "sensor_netwatch"
````

modified version is at my forked copy https://github.com/jajera/homeassistant-mikrotik_router

**Comment by namadori** [comment]
@tomaae any timeframe when this pull request will be merged? It's almost 2 months that the solution to #332 is ready and it seems to have been successfully tested by different users.

**Comment by sidewinder94** [comment]
I can also confirm that it does fix the issue.

Running HaOS 11.4, with a CRS310-8G+2S+ on firmware 7.13.3 and the wireless package disabled.

Any ETA for merging this ?

**Comment by tomasz-soltysik** [comment]
@tomaae if this is not planner for merge i upcomming days, could we get this tagged as beta, so that it is easier to get it and Also test in different setup?

**Review by petr-kozak — COMMENTED** [review]
nice

**Comment by petr-kozak** [comment]
Hi Robert,

what a fast response it is. I was glad to see a solution for the issue I am facing, that was my reaction. But now, when I replace original coordinator.py with your file, I get
{"message":"Invalid handler specified"}

Thank you,
Petr

________________________________

**Comment by rinners** [comment]
I have 2x CRS328 both running RouterOS 7.13.4 on the same network. The integration works for one of them, but not the other.

**Comment by ilwalti** [comment]
Screenshot 2024-02-14 110615
Screenshot 2024-02-14 110103

**Comment by namadori** [comment]
> Since 2 days ago there is a new (small) problem: every 2/3 minutes, both of my Mikrotik with 7.13.4 OS are marked as non up to date in logfile. 

I think you should report this as a separate issue, this is the PR for a different fix and it will get lost once the PR is merged.

**Comment by ilwalti** [comment]
> I think you should report this as a separate issue, this is the PR for a different fix and it will get lost once the PR is merged.
Makes sense. Thanks.
